title: My Simple Weird Blog
description: Search blog structure from which to expand and customise 
markdown: kramdown
baseurl: "sblog"
url: "https://yellowmoss.github.io"
permalink: "/:year/:month/:day/:title"
collections:
  posts:
    output: true
