# title
title: My Simple Weird Blog

# description
description: Search blog structure from which to expand and customise 

# repository name
baseurl: "multiblog"

#
url: "https://yellowmoss.github.io"

# 
collections:
   posts:
      output: true
   articles:
      output: false
   news:
      output: false
   links:
      output: true
