# title
title: My Simple Weird Blog

# description
description: Search blog structure from which to expand and customise 

# repository name
baseurl: "multiblog"

#
url: "https://yellowmoss.github.io"

#
collections_dir: my_collections

# 
collections:
   articles:
      output: true
   news:
      output: true
   links:
      output: true
